apiVersion: v1
kind: ServiceAccount
metadata:
  name: cwagent-prometheus
  namespace: amazon-cloudwatch
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::940168446867:role/multi05-eks-terraform-cwagent-prometheus-role